// Display-only wording for generated observations. Keep source data and exports intact.
export function analysisCopy(value, { csComparison = false } = {}) {
  return String(value ?? "")
    .replace("Réduire les morts gratuites", "Revoir les situations de mort")
    .replace("Les deaths montent trop haut pour transformer les bons plans en games contrôlées.", "Le nombre de morts est élevé dans cette sélection. Ouvre les parties sources pour vérifier les situations à mieux préparer.")
    .replace("L'équipe joue avec moins d'information que l'adversaire, ce qui fragilise setups et entrées rivière.", "Le score de vision est inférieur à celui des adversaires. Vérifie la préparation des objectifs et les entrées en rivière.")
    .replace("C'est le meilleur levier collectif du bloc.", "C’est une piste à vérifier dans les parties sources.")
    .replace(/\bdu prochain bloc\b/g, "de la prochaine session")
    .replace(/\ble prochain bloc\b/g, "la prochaine session")
    .replace(/\bune review\b/g, "un débrief")
    .replace(/\bla review\b/g, "le débrief")
    .replace(/\b1 review ciblée\b/g, "1 débrief ciblé")
    .replace(/\breviews\b/g, "débriefs")
    .replace(/\breview\b/g, "débrief")
    .replace(/\b[Ll]ate game\b/g, "progression en fin de partie")
    .replace(/\b[Ss]ide lane\b/g, "pression sur les voies latérales")
    .replace(/\bgames\b/g, "parties").replace(/\bgame\b/g, "partie")
    .replace(/\bmorts\/G\b/g, "morts par partie")
    .replace(/\bdeaths\b/g, "morts")
    .replace(/\bCS(10|20)\b/g, (_, minute) => csComparison ? `écart de sbires à ${minute} min face au rôle adverse (CS${minute})` : `sbires à ${minute} min (CS${minute})`)
    .replace(/\bau écart de sbires\b/g, "à l’écart de sbires")
    .replace(/\bde écart de sbires\b/g, "d’écart de sbires")
    .replace(/\bKP\b/g, "participation aux éliminations")
    .replace(/\bWR\b/g, "de victoires")
    .replace(/\bVision diff positive\b/g, "Écart de vision positif")
    .replace(/\bVision diff\b/g, "Écart de vision")
    .replace(/\bdrakes\b/g, "dragons").replace(/\bgrubs\b/g, "larves du Néant")
    .replace(/\bsetups?\b/g, "préparation").replace(/\bVOD\b/g, "vidéo de la partie")
    .replace(/\bwave 1-3\b/g, "vagues de sbires 1 à 3")
    .replace(/\bpremier reset\b/g, "premier retour à la base")
    .replace(/\bmove river\b/g, "déplacement en rivière")
    .replace(/\bside faible\b/g, "côté le moins soutenu")
    .replace(/\bwin condition\b/g, "condition de victoire")
    .replace(/\bpattern\b/g, "plan de jeu")
    .replace(/\bmeilleur side\b/g, "meilleur côté");
}
