import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { buildNxt5TimelineSummary } from '../../netlify/functions/_lib/analytics';

const importerSource = readFileSync(new URL('../../importer-app/src/main.js', import.meta.url), 'utf8');
const start = importerSource.indexOf('function timelineFrames(');
const end = importerSource.indexOf('function wardPositionFromEvent(', start);
// Exercise the shipped desktop helper without starting Electron or its IPC.
const importerCsAt = new Function(`${importerSource.slice(start, end)}; return csAtMinuteFromTimeline;`)();

function fixture(duration: number, finalMinute = 15) {
  return {
    info: { gameDuration: duration, participants: [{ participantId: 1, teamId: 100 }] },
    timeline: { info: { frames: [
      { timestamp: 600000, participantFrames: { '1': { minionsKilled: 70, jungleMinionsKilled: 5 } } },
      { timestamp: finalMinute * 60000, participantFrames: { '1': { minionsKilled: 110, jungleMinionsKilled: 4 } } }
    ] } }
  };
}

describe('CS milestones reflect an observed game minute', () => {
  it('does not fabricate CS20 from the last frame of a fifteen-minute game', () => {
    const match = fixture(900);
    expect(buildNxt5TimelineSummary(match).csMilestones['1']).toMatchObject({ cs10: 75, cs20: null });
    expect(importerCsAt(match.timeline, 1, 20, 900)).toBeNull();
    expect(importerCsAt(match.timeline, 1, 10, 900)).toBe(75);
  });

  it('does not use an incomplete timeline as a twentieth-minute sample', () => {
    const match = fixture(1800);
    expect(buildNxt5TimelineSummary(match).csMilestones['1'].cs20).toBeNull();
    expect(importerCsAt(match.timeline, 1, 20, 1800)).toBeNull();
  });

  it('retains an available sample at exactly twenty minutes', () => {
    const match = fixture(1200, 20);
    expect(buildNxt5TimelineSummary(match).csMilestones['1'].cs20).toBe(114);
    expect(importerCsAt(match.timeline, 1, 20, 1200)).toBe(114);
  });

  it('repairs a cached milestone generated by an older importer for a short game', () => {
    const match = { info: { gameDuration: 900, participants: [] }, nxt5: {
      timelineSummary: { available: true, csMilestones: { '1': { cs10: 75, cs20: 114 } } }
    } };
    expect(buildNxt5TimelineSummary(match).csMilestones['1']).toEqual({ cs10: 75, cs20: null });
    expect(match.nxt5.timelineSummary.csMilestones['1'].cs20).toBe(114);
  });
});
