import { escapeHtml, getMetadata, renderMetadata } from "../src/seo/metadata.js";

export function resolveSeoConfig(env = process.env) {
  const url = new URL(env.PUBLIC_SITE_URL || "https://nxt5.org");
  if (!["https:", "http:"].includes(url.protocol) || url.username || url.password || url.pathname !== "/" || url.search || url.hash) throw new Error("PUBLIC_SITE_URL must be an HTTP(S) origin without credentials, path, query or fragment.");
  return { origin: url.origin, noindex: Boolean(env.CONTEXT && env.CONTEXT !== "production") };
}

export function withMetadata(html, path, config) {
  if (!html.includes("<!--seo:start-->")) throw new Error("Missing SEO metadata marker in HTML template.");
  return html.replace(/<!--seo:start-->[\s\S]*?<!--seo:end-->/, () => `<!--seo:start-->\n    ${renderMetadata(getMetadata(path, config))}\n    <!--seo:end-->`);
}

export function sitemapXml(paths, config) {
  const entries = config.noindex ? [] : paths;
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries.map((path) => `  <url><loc>${escapeHtml(`${config.origin}${path}`)}</loc></url>`).join("\n")}\n</urlset>\n`;
}

export function robotsTxt(config) {
  // Private HTML remains crawlable so that its noindex directive can be read.
  return `User-agent: *\nAllow: /\nDisallow: /.netlify/functions/\nDisallow: /api/\n${config.noindex ? "" : `\nSitemap: ${config.origin}/sitemap.xml\n`}`;
}

export function redirectRules(publicPaths, privatePaths) {
  return [
    "# Generated by tools/prerender.mjs. Keep routing in sync with the application.",
    "/index.html / 301!",
    "/inscription /creer-un-compte 301!",
    ...publicPaths.filter((path) => path !== "/").map((path) => `${path}.html ${path} 301!`),
    ...privatePaths.filter((path) => path !== "/inscription").map((path) => `${path} /app-shell.html 200`),
    ...["/profil", "/mon-profil", "/draft"].map((path) => `${path}/* /app-shell.html 200`),
    "/* /404.html 404",
    "",
  ].join("\n");
}
