import { escapeHtml, getMetadata, PUBLIC_METADATA, renderMetadata, SITE_ORIGIN } from "../src/seo/metadata.js";

export function resolveSeoConfig(env = process.env) {
  // Deployment URLs are never canonical. Fail rather than accidentally index a preview.
  if (env.PUBLIC_SITE_URL && env.PUBLIC_SITE_URL.replace(/\/$/, "") !== SITE_ORIGIN) {
    throw new Error(`PUBLIC_SITE_URL must be the canonical production origin ${SITE_ORIGIN}.`);
  }
  return { noindex: Boolean(env.CONTEXT && env.CONTEXT !== "production") };
}

export function withMetadata(html, path, config) {
  if (!html.includes("<!--seo:start-->")) throw new Error("Missing SEO metadata marker in HTML template.");
  return html.replace(/<!--seo:start-->[\s\S]*?<!--seo:end-->/, () => `<!--seo:start-->\n    ${renderMetadata(getMetadata(path, config))}\n    <!--seo:end-->`);
}

export function sitemapXml(config) {
  const paths = config.noindex ? [] : Object.keys(PUBLIC_METADATA);
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${paths.map(path => `  <url><loc>${escapeHtml(`${SITE_ORIGIN}${path}`)}</loc></url>`).join("\n")}\n</urlset>\n`;
}

export function robotsTxt(config) {
  // Do not Disallow private HTML: crawlers must be able to read its noindex.
  return `User-agent: *\nAllow: /\nDisallow: /.netlify/functions/\nDisallow: /api/\n${config.noindex ? "" : `\nSitemap: ${SITE_ORIGIN}/sitemap.xml\n`}`;
}

export function redirectRules(privatePaths, dynamicPaths) {
  return [
    "# Generated by tools/prerender.mjs from public metadata and application routes.",
    "/index.html / 301!",
    "/inscription /creer-un-compte 301!",
    ...Object.keys(PUBLIC_METADATA).filter(path => path !== "/").map(path => `${path}.html ${path} 301!`),
    ...privatePaths.filter(path => path !== "/inscription").flatMap(path => [`${path} /app-shell.html 200`, `${path}/ /app-shell.html 200`]),
    ...dynamicPaths.map(path => `${path}/* /app-shell.html 200`),
    // Existing CDN assets and Netlify Functions are not shadowed (no force flag).
    "/* /404.html 404",
    "",
  ].join("\n");
}

export function robotsHeaders(config, privatePaths, dynamicPaths) {
  if (config.noindex) return "/*\n  X-Robots-Tag: noindex, follow\n";
  return [...new Set(["/app-shell.html", "/404.html", "/404", ...privatePaths.flatMap(path => [path, `${path}/`]), ...dynamicPaths.map(path => `${path}/*`)])]
    .map(path => `${path}\n  X-Robots-Tag: noindex, follow\n`).join("\n");
}
